// Generated by CoffeeScript 1.9.2
describe("Neuron", function() {
  it("is a function", function() {
    return expect(typeof Neuron).toBe('function');
  });
  return it("new Neuron() returns an object", function() {
    var neuron;
    neuron = new Neuron();
    return expect(typeof neuron).toBe('object');
  });
});
